<a href="https://colab.research.google.com/github/gmanojkumar402-max/Manoj-colab-notebooks/blob/main/mini_batch_gradient_decent_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [119]:
X,y = load_diabetes(return_X_y=True)

In [120]:
print(X.shape)

(442, 10)


In [121]:
print(y.shape)


(442,)


In [122]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [123]:
LR = LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

In [124]:
y_pred = LR.predict(X_test)
r2_score(y_test,y_pred)

0.4526027629719195

In [125]:
LR.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [126]:
LR.intercept_

np.float64(151.34560453985995)

In [127]:
import random
class MBGDRegressor:
  def __init__(self,batch_size,learning_rate =0.01,epochs=100):
    self.coef_= None
    self.intercept_ = None
    self.lr = learning_rate
    self.batch_size = batch_size
    self.epochs = epochs
  def fit(self,X_train,y_train):
    # initializing the intercept = 0 & coefficients as 1
    self.intercept_ = 0
    self.coef_ = np.ones(X_train.shape[1])
    for i in range(self.epochs):
      for j in range(int(X_train.shape[0]/self.batch_size)):
        # Running the above Loop vased on batch size
        # lets generate random idx below between range of 0 - batch_size
        idx = random.sample(range(X_train.shape[0]),self.batch_size)
        # prediction happens based on the batch size
        y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
        # above we have calculated y_predict for the random 10 rows
        intercept_der = -2 * np.mean(y_train[idx] - y_hat)
        self.intercept_ = self.intercept_ - (self.lr * intercept_der)
        coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
        self.coef_ = self.coef_ - (self.lr * coef_der)

    print(self.intercept_,self.coef_)
  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_


In [128]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [129]:
mbr.fit(X_train,y_train)

149.34531054352726 [  49.51141514 -174.93412842  462.40118065  313.3895679   -51.87523769
 -105.66256754 -206.37369564  140.38747341  351.53216057  124.25664887]


In [130]:
y_pred = mbr.predict(X_test)

In [131]:
r2_score(y_test,y_pred)

0.4555270372832696

In [132]:
np.ones(X_train.shape[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [133]:
random.sample(range (1, 100),10)

[93, 28, 84, 87, 61, 11, 9, 43, 27, 4]

In [134]:
X_train[[30, 32, 74, 51, 18, 76, 79, 64, 2, 43]]

array([[ 0.01264814, -0.04464164,  0.01535029, -0.03321323,  0.04108558,
         0.03219301, -0.00290283, -0.00259226,  0.04506655, -0.06735141],
       [-0.03457486, -0.04464164, -0.0374625 , -0.06075604,  0.02044629,
         0.04346635, -0.01394774, -0.00259226, -0.03074792, -0.07149352],
       [ 0.01628068, -0.04464164, -0.04716281, -0.00222757, -0.01945635,
        -0.04296262,  0.03391355, -0.03949338,  0.02736405,  0.02791705],
       [-0.0854304 ,  0.05068012, -0.04069594, -0.03321323, -0.08137423,
        -0.06958024, -0.00658447, -0.03949338, -0.05780303, -0.04249877],
       [ 0.04170844,  0.05068012, -0.04392938,  0.0631866 , -0.00432087,
         0.01622244, -0.01394774, -0.00259226, -0.03452178,  0.01134862],
       [ 0.01628068,  0.05068012,  0.00241654, -0.00567042, -0.00569682,
         0.01089891, -0.05076412,  0.03430886,  0.02268774, -0.03835666],
       [ 0.06713621, -0.04464164, -0.03854032, -0.02632753, -0.03183992,
        -0.02636575,  0.00814208, -0.03949338

In [135]:
X_train[[30, 32, 74, 51, 18, 76, 79, 64, 2, 43]].shape

(10, 10)

In [136]:
y_train[[30, 32, 74, 51, 18, 76, 79, 64, 2, 43]]

array([242., 128., 200.,  71.,  71., 245., 127., 292., 280., 232.])

In [137]:
y_train[[30, 32, 74, 51, 18, 76, 79, 64, 2, 43]].shape

(10,)

In [138]:
int(353/10)

35

Let's impliment MBGD using SDG in sklearn
Note: Here we don't have direct option to set the batch size we have a trick to set the batch size

In [139]:
sgd = SGDRegressor(learning_rate = "constant",eta0 = 0.1)

In [140]:
batch_size = 35
for i in range(100):
  idx = random.sample(range(X_train.shape[0]),batch_size)
  sgd.partial_fit(X_train[idx],y_train[idx]) # using partial fit we can take subset of X-train and y_train

In [141]:
sgd.coef_

array([  63.50988929, -108.87078666,  362.16840718,  266.0430364 ,
          0.72759214,  -38.37817472, -174.96028896,  138.14372489,
        276.36961149,  139.90204721])

In [142]:
sgd.intercept_

array([146.59151369])

In [143]:
r2_score(y_test,sgd.predict(X_test))

0.4378697871297139