<a href="https://colab.research.google.com/github/gmanojkumar402-max/Manoj-colab-notebooks/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is used for scientific computing in python

Numpy provides multidimensional array object

An array is an object that stores a group of values in an ordered manner. These values are typically of the same data type and can be accessed using an index.

Key Characteristics of Arrays

•	Ordered collection → elements are stored in a sequence

•	Indexed → each element has a position (starting from 0 in Python)

•	Same data type → usually stores elements of the same type

•	Efficient storage → especially for numerical data


The array object in numpy is called as ndarray.

ndarray--> N-dimensional (can have 1D, 2D, 3D, or more dimensions) array


Each column in a DataFrame is a Pandas Series, which internally uses NumPy arrays for storing data.

Arrays do not inherently have columns and rows—they are just structured data.

The .values attribute of a DataFrame returns a NumPy array containing all the data (both rows and columns), not just columns.

A DataFrame is a 2D structure (rows × columns), so when you convert it using .values, we get:

A 2D NumPy ndarray from NumPy

In [2]:
import pandas as pd
import numpy as np
data = {'A':[1,2], 'B':[2,3]}
df = pd.DataFrame(data)
df

,A,B
0,1,2
1,2,3


Now let's print .values attribute of pandas dataframe that returns array

In [5]:
# Without rows and columns
print(df.values)

[[1 2]
 [2 3]]


The above result is a 2D Numpy array that includes both rows and columns

NumPy arrays are created using the array() function, which converts input data like lists or tuples into an ndarray object. It is recommended to use elements of the same data type for efficient computation.

In [6]:
# let's create a series
a = [1,2,3,4,5]
s = pd.Series(a)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


numpy.ndim is predefined variable which is used to check the dimensiopns of an array

In [9]:
# now in the same way we will use list to create an array
import numpy as np
age = 44
value = np.array(age)
print(value, type(value))
print(value.ndim)

44 <class 'numpy.ndarray'>
0


In [11]:
details = [10, 20, 30, 40]
array = np.array(details)
print(array)
print(array.ndim)

[10 20 30 40]
1


In [12]:
details = [[1,2],[3,4]]
array = np.array(details)
print(array)
print(array.ndim)

[[1 2]
 [3 4]]
2


In [13]:
import numpy as np
a =[[1,2],[3,4],[5,6]]
array= np.array(a)
print(array)
print(array.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


We can access the data in a list, tuple data structure using indexing, slicing, loop but we cannot access the data in set data structure using indexing

We can access numpy array values by using indexing and slicing.

Numpy array having indexing nature.

Numpy array index start with 0.


In [14]:
import numpy as np
a = [1,2,3]
result = np.array(a)
print(result[1])

2


In [21]:
import numpy as np
a = [1,2,3,4,5]
result = np.array(a)
print(result[:2])


[1 2]


In [22]:
import numpy as np
a = [1,2,3,4,5]
result = np.array(a)
print(result[0:2])

[1 2]


In [23]:
import numpy as np
a = [1,2,3,4,5]
result = np.array(a)
print(result[3:])

[4 5]


In [24]:
# Creating matrix and selecting elements
import numpy as np
matrix = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(matrix)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [26]:
print(matrix[0,0])

1


In [27]:
print(matrix[0,1])

2


In [28]:
print(matrix[1,0])

2


In [29]:
print(matrix[2,0])

3


In [31]:
# Index Error
a = [1,2,3,4,5]
array = np.array(a)
print(array)
print(array[5])

[1 2 3 4 5]


IndexError: index 5 is out of bounds for axis 0 with size 5

In [33]:
# Creating a array with all zeros
import numpy as np
sales = np.zeros(5)
print(sales)
# output is float

[0. 0. 0. 0. 0.]


In [34]:
# creating an array with all 1
import numpy as np
sales = np.ones(5)
print(sales)
# output is float

[1. 1. 1. 1. 1.]


In [36]:
# array attributes
# shape attributes
a = [1,2,3,4,5]
array = np.array(a)
print(array)
array.shape # --> 1D array with 5 values or elements

[1 2 3 4 5]


(5,)

In [38]:
a = [[1,2],[3,4]]
array = np.array(a)
print(array)
array.shape # --> 2D array with 2 ros and 2 columns

[[1 2]
 [3 4]]


(2, 2)

In [40]:
# ndim attribute
a = [[1,2],[3,4],[4,5]]
array = np.array(a)
print(array)
array.ndim

[[1 2]
 [3 4]
 [4 5]]


2

In [42]:
# T attribute also a constant--> converts rows into columns and viceversa
a = [[1,2],[3,4],[5,6]]
array= np.array(a)
print(array)
array.T

[[1 2]
 [3 4]
 [5 6]]


array([[1, 3, 5],
       [2, 4, 6]])

In [44]:
# Numpy array methods
# min method
a = [1,2,3,4,5]
array = np.array(a)
print(array)
print(array.min())

[1 2 3 4 5]
1


In [46]:
# max method
a = [1,2,3,4,5]
array = np.array(a)
print(array)
print(array.max())

[1 2 3 4 5]
5


In [47]:
# Sum method
a = [1,2,3,4,5]
array = np.array(a)
print(array)
print(array.sum())

[1 2 3 4 5]
15


In [48]:
a = [[1,2],[2,3],[3,4]]
array = np.array(a)
print(array)
print(array.sum())

[[1 2]
 [2 3]
 [3 4]]
15


In [50]:
# reshape method used to change the shape of an array.
a = [1,2,3,4,5]    # --> 1 row with 5 elements
array = np.array(a)
print(array)
print(array.reshape(5,1))
# output is 5 rows with 1 element each

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [55]:
a = [[1,2],[3,4],[5,6]]
array = np.array(a)
print(array)
print(array.reshape(2,3))
print()
print(array.reshape(1,6))
print()
print(array.reshape(6,1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]

[[1 2 3 4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [58]:
# sort method
a = [[17,9,6],[3,5,19],[21,10,13]]
result = np.sort(a)
result

array([[ 6,  9, 17],
       [ 3,  5, 19],
       [10, 13, 21]])

In [56]:
# functions
# count_nonzero function
import numpy as np
a = [[10,0,30],[0,50,0]]
result = np.count_nonzero(a)
result

3

In [60]:
# flatten method keeps all values in one dimension array
import numpy as np
details = [[10,20,30],[3,2,1],[9,7,5]]
array = np.array(details)
print(array)
print(array.flatten())

[[10 20 30]
 [ 3  2  1]
 [ 9  7  5]]
[10 20 30  3  2  1  9  7  5]


In [62]:
# adding value to array of values
import numpy as np
details = np.array([[2,3,5],[5,3,1],[9,7,5]])
print(details)
print(details+2)

[[2 3 5]
 [5 3 1]
 [9 7 5]]
[[ 4  5  7]
 [ 7  5  3]
 [11  9  7]]


In [64]:
# Diagonal method returns all diagonal elements of a Matrix
matrix = np.array([[2,4,6],[5,78,3],[3,6,8]])
print(matrix)
print()
print(matrix.diagonal())

[[ 2  4  6]
 [ 5 78  3]
 [ 3  6  8]]

[ 2 78  8]


In [68]:
# Trace of a Matrix is the sum of the diagonal elements
import numpy as np
matrix = np.array([[1,2,],[5,3],[8,5]])
print(matrix)
print()
print(matrix.trace())

[[1 2]
 [5 3]
 [8 5]]

4


In [69]:
matrix = np.array([[1,2,5],[5,3,7],[8,5,9]])
print(matrix)
print()
print(matrix.trace())

[[1 2 5]
 [5 3 7]
 [8 5 9]]

13


In [71]:
# Adding and Subtracting Matrices using add and substract function
import numpy as np
matrix_a = np.array([[1,2,4],[3,5,2],[2,4,1]])
matrix_b = np.array([[5,3,6],[3,6,3],[6,4,2]])
print(matrix_a)
print()
print(matrix_b)
matrix_a + matrix_b

[[1 2 4]
 [3 5 2]
 [2 4 1]]

[[5 3 6]
 [3 6 3]
 [6 4 2]]


array([[ 6,  5, 10],
       [ 6, 11,  5],
       [ 8,  8,  3]])

In [72]:
print(np.add(matrix_a,matrix_b))

[[ 6  5 10]
 [ 6 11  5]
 [ 8  8  3]]


In [74]:
print(np.subtract(matrix_a,matrix_b))

[[-4 -1 -2]
 [ 0 -1 -1]
 [-4  0 -1]]


In [75]:
import numpy as np
matrix_a = np.array([[1,2,4],[3,5,2],[2,4,1]])
matrix_b = np.array([[5,3,6],[3,6,3],[6,4,2]])
print(matrix_a)
print()
print(matrix_b)
matrix_a - matrix_b

[[1 2 4]
 [3 5 2]
 [2 4 1]]

[[5 3 6]
 [3 6 3]
 [6 4 2]]


array([[-4, -1, -2],
       [ 0, -1, -1],
       [-4,  0, -1]])

Vectorization

In [3]:
# Vectorization
import numpy as np
a = [[1,2,3,], [4,5,6], [7,8,9]]
sales = np.array(a)
print(sales)
print()
print(sales + 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# now without numpy if we want to perform the same operation
# Pure Python-style looping
# creating an empty list
empty_list = []
for rows in sales:
  new_row = []
  for val in rows:
    new_row.append(val + 2)
  empty_list.append(new_row)
print(empty_list)

[[np.int64(3), np.int64(4), np.int64(5)], [np.int64(6), np.int64(7), np.int64(8)], [np.int64(9), np.int64(10), np.int64(11)]]


In [9]:
# Pure Python-style looping
empty_list = []
for rows in sales:
  new_rows = []
  for values in rows:
    new_rows.append(values -2)
  empty_list.append(new_rows)
print(empty_list)

[[np.int64(-1), np.int64(0), np.int64(1)], [np.int64(2), np.int64(3), np.int64(4)], [np.int64(5), np.int64(6), np.int64(7)]]


In [11]:
# (NumPy-powered looping)
empty_list = []
for values in sales:
  empty_list.append(values+2)
print(empty_list)

[array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [14]:
# Explanation
empty_list = []
for rows in sales: # We are iterating through each row of the array
  new_rows = []       # creating an empty list for every new row
  for val in rows:  # we are iterating through each value in that row
    new_rows.append(val + 2) # we add val + 2 and store it in new rows
  empty_list.append(new_rows)  # we are adding new rows to empty list
print(empty_list)  # finally printing the empty list

[[np.int64(3), np.int64(4), np.int64(5)], [np.int64(6), np.int64(7), np.int64(8)], [np.int64(9), np.int64(10), np.int64(11)]]


Broadcasting

Broadcasting in NumPy allows arithmetic operations between arrays of different shapes by automatically expanding the smaller array to match the larger one, without explicitly copying data.

In [15]:
# Broadcasting
import numpy as np

sales = np.array([
    [100, 200, 150],
    [120, 220, 130],
    [90,  210, 160]
])

sales + 10

array([[110, 210, 160],
       [130, 230, 140],
       [100, 220, 170]])

In [16]:
# Add different bonus per product
bonus = np.array([5,10,15])
print(sales + bonus)

[[105 210 165]
 [125 230 145]
 [ 95 220 175]]


In [17]:
# Add bonus per day (row-wise)
bonus = np.array([[5],
                  [10],
                  [15]])
print(sales + bonus)

[[105 205 155]
 [130 230 140]
 [105 225 175]]


In [18]:
# Broadcasting using numpy interference in python code
import numpy as np

sales = np.array([
    [100, 200, 150],
    [120, 220, 130],
    [90,  210, 160]
])

bonus = [10, 20, 30]
empty_list = []
for rows in sales:
  new_rows = []
  for val in rows:
    new_rows.append(val + bonus)
  empty_list.append(new_rows)
print(empty_list)

[[array([110, 120, 130]), array([210, 220, 230]), array([160, 170, 180])], [array([130, 140, 150]), array([230, 240, 250]), array([140, 150, 160])], [array([100, 110, 120]), array([220, 230, 240]), array([170, 180, 190])]]


In [21]:
bonus = [10, 20, 30]

empty_list = []

for row in sales:
    new_row = []
    for i in range(len(row)):
      new_row.append(row[i] + bonus[i])
    empty_list.append(new_row)
print(empty_list)

[[np.int64(110), np.int64(220), np.int64(180)], [np.int64(130), np.int64(240), np.int64(160)], [np.int64(100), np.int64(230), np.int64(190)]]


In [20]:
a = [1,2,3,4,5]
range(len(a))

range(0, 5)

In [22]:
a = range(5)
print(a)

range(0, 5)


In [23]:
# adding per row [[10], [20], [30]]
bonus = [10, 20, 30]
empty_list = []
for i in range(len(sales)):
  new_row = []
  for val in sales[i]:
    new_row.append(val + bonus[i])
  empty_list.append(new_row)
print(empty_list)

[[np.int64(110), np.int64(210), np.int64(160)], [np.int64(140), np.int64(240), np.int64(150)], [np.int64(120), np.int64(240), np.int64(190)]]


Boolean index

Boolean indexing in NumPy allows filtering or modifying array elements based on conditions. It works by creating a Boolean mask (True/False) and selecting elements where the condition is True.

In [24]:
# Boolean index
# get values > 150
import numpy as np
sales = np.array([10, 20, 30, 40, 50])
print(sales)

[10 20 30 40 50]


In [25]:
# creating a condition
sales > 20

array([False, False,  True,  True,  True])

In [26]:
# To select values where condition is True
sales[sales > 20]

array([30, 40, 50])

In [27]:
# creating a condition
sales < 40

array([ True,  True,  True, False, False])

In [28]:
# To select values where condition is True
sales[sales < 40]

array([10, 20, 30])

In [29]:
# 2D Example
sales = np.array([
    [100, 200, 150],
    [120, 80, 130],
    [90, 210, 160]
])
sales > 150
sales[sales > 150]

array([200, 210, 160])

In [31]:
# Replace low values
sales[sales < 100] = 0
sales

array([[100, 200, 150],
       [120,   0, 130],
       [  0, 210, 160]])

Boolean indexing will help in Removing invalid data, Filter customers, Handle missing values, Feature engineering

Axis Operations

Axis in NumPy defines the direction along which operations are performed. Axis 0 refers to column-wise operations (down rows), while axis 1 refers to row-wise operations (across columns).

In [32]:
import pandas as pd

sales = np.array([[100, 200, 150],
                  [120, 220, 130],
                  [90, 210, 160]])
sales

array([[100, 200, 150],
       [120, 220, 130],
       [ 90, 210, 160]])

Axis tells NumPy the direction along which an operation should be performed.

In NumPy:

axis = 0 → column-wise (downwards)

axis = 1 → row-wise (across)

In [33]:
sales.sum(axis = 0)

array([310, 630, 440])

In [34]:
sales.sum(axis = 1)

array([450, 470, 460])

In [35]:
# product wise average
sales.mean(axis = 0)

array([103.33333333, 210.        , 146.66666667])

In [36]:
# day wise average
sales.mean(axis = 1)

array([150.        , 156.66666667, 153.33333333])

In [37]:
# max value per column
sales.max(axis = 0)

array([120, 220, 160])

In [38]:
# max value per row
sales.max(axis = 1)

array([200, 220, 210])

Random Module

The random module in NumPy is used to generate random numbers and arrays.

In [39]:
# creating a random dataset
import numpy as np
data = np.random.rand(3,3)
print(data)

[[0.8914276  0.02136373 0.7975696 ]
 [0.17852863 0.17191698 0.40735433]
 [0.9652737  0.91751298 0.60868758]]


In [41]:
# creating random integers
data = np.random.randint(50, 100, size = (3,3))
print(data)

[[70 70 51]
 [98 89 94]
 [68 56 63]]


Generate 9 random integers between 50 and 100

Arrange them in a 3 × 3 array (3 rows and 3 columns)

In [43]:
# Random choice
data = np.array([10, 20, 30, 40, 50])
sample = np.random.choice(data, size = 3)
print(sample)

[30 10 20]


np.random.seed() is used to initialize the random number generator so that the same random values are generated every time the code is executed, ensuring reproducibility.

In [44]:
# Set Seed
np.random.seed(42)
data = np.random.randint(1, 10, size = (2,2))
print(data)

[[7 4]
 [8 5]]


In [45]:
# seeing if same random values are generated or not
print(data)

[[7 4]
 [8 5]]


Normal Distribution

A normal distribution is a type of data distribution where values are spread symmetrically around the mean (average), forming a bell-shaped curve.

In [46]:
# Normal Distribution
data = np.random.randn(3,3)
print(data)

[[-0.23415337 -0.23413696  1.57921282]
 [ 0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227]]


Random module is used to Generate dummy data, Train/test split, Initialize ML models and Simulations

The NumPy random module is used to generate random numbers and datasets. It is widely used in data science for simulations, sampling, and machine learning tasks. Functions like rand, randint, choice, and randn help create different types of random data.

In [49]:
data = np.random.randn(3)
print(data)
print()
print(data.min(), data.max())

[-1.4123037   1.46564877 -0.2257763 ]

-1.4123037013352915 1.465648768921554


In a normal distribution, values are symmetrically distributed around the mean, meaning the left and right sides have the same shape and probability distribution, but not necessarily the exact same number of values.